spring:
  datasource:
    url: jdbc:mysql://139.155.80.168:3306/blogs?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: blogs
    password: blogs
    type: com.alibaba.druid.pool.DruidDataSource